### PR TITLE
change name in title

### PR DESCRIPTION
**Pull request by ClaireCombastel**

### CODE REVIEW

**Review by nicolasvauche — CHANGES_REQUESTED** [review]
Please remove .idea

**Review by nicolasvauche — CHANGES_REQUESTED** [review]
Please remove .DS_Store file**s**

**Review by nicolasvauche — APPROVED** [review]

**Review by Bastien-Baloup — APPROVED** [review]
you should add .idea to .gitignore

**Review by NarjesJOMAA — APPROVED** [review]

**Review by tonybengue — APPROVED** [review]
Super

**Pull request merged**
